'use client'

import { useEffect } from 'react'

import { usePageTitle } from '@/hooks/use-page-title'

import * as SC from './styles'

const TermsTemplate = () => {
  const { setTitle } = usePageTitle()

  useEffect(() => {
    setTitle('Terms of Service')
  }, [setTitle])

  return (
    <SC.PageWrapper>
      <SC.ContentPageWrapper>
        <SC.Header>
          <SC.Title>Terms of Service</SC.Title>

          <SC.LastUpdated>Last updated: May 11, 2026</SC.LastUpdated>
        </SC.Header>

        <SC.Section>
          <SC.SectionTitle>Acceptance of Terms</SC.SectionTitle>

          <SC.Paragraph>
            By accessing or using DermaTrack, you agree to be bound by these
            Terms of Service and all applicable laws and regulations. If you do
            not agree with any part of these terms, you must not use the
            platform. Your continued use of DermaTrack indicates your acceptance
            of any updates or modifications to these Terms.
          </SC.Paragraph>
        </SC.Section>

        <SC.Section>
          <SC.SectionTitle>Eligibility</SC.SectionTitle>

          <SC.Paragraph>
            You must be at least 18 years old to use DermaTrack. If you are
            under 18, you may only use the platform with the involvement and
            consent of a parent or legal guardian who agrees to be bound by
            these Terms. By using the service, you represent and warrant that
            you meet these eligibility requirements.
          </SC.Paragraph>
        </SC.Section>

        <SC.Section>
          <SC.SectionTitle>Medical Disclaimer</SC.SectionTitle>

          <SC.Paragraph>
            DermaTrack is designed to support personal skin tracking and
            informational insights only. It does not provide medical advice,
            diagnosis, or treatment. Any content, suggestions, or outputs
            generated by the platform are not a substitute for professional
            medical evaluation. Always seek advice from a qualified healthcare
            provider regarding any medical condition or treatment decisions.
          </SC.Paragraph>
        </SC.Section>

        <SC.Section>
          <SC.SectionTitle>User Accounts</SC.SectionTitle>

          <SC.Paragraph>
            You are responsible for maintaining the confidentiality of your
            account credentials and for all activities that occur under your
            account. You agree to notify us immediately of any unauthorized
            access or suspected security breach. We are not liable for any loss
            or damage resulting from your failure to secure your account.
          </SC.Paragraph>
        </SC.Section>

        <SC.Section>
          <SC.SectionTitle>Acceptable Use</SC.SectionTitle>

          <SC.Paragraph>
            You agree to use DermaTrack only for lawful purposes and in
            accordance with these Terms. You must not attempt to interfere with
            the platform’s operation, gain unauthorized access to systems,
            exploit vulnerabilities, reverse engineer the service, or use it to
            distribute harmful or malicious software. Any abusive, fraudulent,
            or illegal activity may result in suspension or termination of your
            account.
          </SC.Paragraph>
        </SC.Section>

        <SC.Section>
          <SC.SectionTitle>Intellectual Property</SC.SectionTitle>

          <SC.Paragraph>
            All content, features, and functionality of DermaTrack, including
            but not limited to software, design, branding, and logos, are the
            exclusive property of DermaTrack or its licensors. You may not copy,
            modify, distribute, or create derivative works without prior written
            permission.
          </SC.Paragraph>
        </SC.Section>

        <SC.Section>
          <SC.SectionTitle>Limitation of Liability</SC.SectionTitle>

          <SC.Paragraph>
            To the maximum extent permitted by law, DermaTrack and its
            affiliates shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages, including loss of data,
            profits, or goodwill, arising out of or related to your use of the
            platform. Your use of the service is at your sole risk.
          </SC.Paragraph>
        </SC.Section>

        <SC.Section>
          <SC.SectionTitle>Service Availability</SC.SectionTitle>

          <SC.Paragraph>
            We strive to keep DermaTrack available and operational at all times,
            but we do not guarantee uninterrupted access. The service may be
            temporarily unavailable due to maintenance, updates, or technical
            issues without prior notice.
          </SC.Paragraph>
        </SC.Section>

        <SC.Section>
          <SC.SectionTitle>Termination</SC.SectionTitle>

          <SC.Paragraph>
            We reserve the right to suspend or terminate your access to
            DermaTrack at any time, without prior notice, if we reasonably
            believe that you have violated these Terms or engaged in harmful
            conduct. Upon termination, your right to use the platform will
            immediately cease.
          </SC.Paragraph>
        </SC.Section>

        <SC.Section>
          <SC.SectionTitle>Changes to Terms</SC.SectionTitle>

          <SC.Paragraph>
            We may update or modify these Terms from time to time to reflect
            changes in our services or legal obligations. When changes occur, we
            will update the “Last updated” date. Continued use of DermaTrack
            after such updates constitutes acceptance of the revised Terms.
          </SC.Paragraph>
        </SC.Section>

        <SC.Section>
          <SC.SectionTitle>Contact</SC.SectionTitle>

          <SC.Paragraph>
            If you have any questions about these Terms, please contact us at
            support@dermatrack.com. We will do our best to respond promptly and
            address your concerns.
          </SC.Paragraph>
        </SC.Section>
      </SC.ContentPageWrapper>
    </SC.PageWrapper>
  )
}

export default TermsTemplate
