sonar.projectKey=dermatrack_frontend
sonar.projectName=DermaTrack Frontend
sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/__tests__/**
sonar.coverage.exclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.styles.ts,**/*.styles.tsx,**/styles.ts,**/styles.tsx,src/app/**/*.ts,src/app/**/*.tsx,src/components/templates/**/*.ts,src/components/templates/**/*.tsx,src/context/auth/index.tsx,src/lib/client-layout.tsx,src/lib/registry.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info